apiVersion: v1
kind: Deployment
metadata:
  name: partyapi-deployment
spec:
  selector:
    matchLabels:
      app: partyapi
  replicas: 3
  template:
    metadata:
      labels:
        app: partyapi
    spec:
      containers:
        - name: partyapi
          image: parulgohil27/partyapi:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
---
apiVersion: v1 
kind: Service
metadata:
  name: partyapi-svc
spec:
  type: LoadBalancer
  selector:
    app: partyapi
  ports:
    - port: 3306 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service