apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: mysql-deployment
spec:
  serviceName: mysql-pod
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
      name: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-deployment
        selector: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        ports:
          - containerPort: 3306
        args: ["--ignore-db-dir=lost+found"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom :
              secretKeyRef :
                name : mysql-secrets
                key :  password
          - name: MYSQL_DATABASE 
            valueFrom :
              configMapKeyRef :
                name : db-config
                key :  dbName
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql/data
    volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
