apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        selector: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args: ["--ignore-db-dir=lost+found"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom :
              secretKeyRef :
                name : mysql-secrets
                key :  password
          - name: MYSQL_DATABASE 
            valueFrom :
              configMapKeyRef :
                name : db-config
                key :  dbName
        ports:
          - containerPort: 3306
        volumeMounts:
<<<<<<< HEAD
        - name: data-volume
          mountPath: /var/lib/mysql/data
      volumes:
      - name: data-volume
        PersistentVolumeClaim:
            claimName: mysql-pvc
=======
          - name: mysql-pvc
            mountPath: /var/lib/mysqlpersistdata
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
>>>>>>> b35a8ac17edce478305b3b5780e136202d0a4668
