apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        selector: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom :
              secretKeyRef :
                name : mysql-secrets
                key :  password

          - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
            valueFrom :
              configMapKeyRef :
                name : db-config
                key :  dbName
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: pvc
            mountPath: /data/mysql
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi