apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: mysql-deployment
spec:
  serviceName: mysql-pod
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
      name: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-deployment
        name: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        # args:
        #   - "--ignore-db-dir=lost+found"
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom :
              secretKeyRef :
                name : mysql-secrets
                key :  password
          - name: MYSQL_DATABASE 
            valueFrom :
              configMapKeyRef :
                name : db-config
                key :  dbName
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysqldb2
          # - name: mysql-initdb
          #   mountPath: /docker-entrypoint-initdb.d
      volumes:
        # - name: mysql-initdb
        #   configMap:
        #     name: db-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc