apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    name: datastore
    app: mysql
spec:
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1 Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
