apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    name: datastore
    app: mysql
spec:
  resources:
    requests:
      storage:
    limits:
      storage:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
